name: jinx-tracker-stack
services:
  jinx-tracker:
    container_name: jinx-tracker
    hostname: jinx-tracker
    build: .
    image: elementalmp4/jinx-tracker
    volumes:
    - ./game.bin:/app/game.bin
    ports:
      - "7003:7003"